package api

import (
	"github.com/dotbinio/taskwarrior-api/internal/api/handlers"
	"github.com/dotbinio/taskwarrior-api/internal/api/middleware"
	"github.com/dotbinio/taskwarrior-api/internal/auth"
	"github.com/dotbinio/taskwarrior-api/internal/config"
	"github.com/dotbinio/taskwarrior-api/internal/taskwarrior"
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/dotbinio/taskwarrior-api/docs" // This is generated by swag init
)

// SetupRouter creates and configures the Gin router
func SetupRouter(cfg *config.Config, twClient *taskwarrior.Client, validator *auth.TokenValidator) *gin.Engine {
	// Set Gin mode
	if cfg.Logging.Level == "debug" {
		gin.SetMode(gin.DebugMode)
	} else {
		gin.SetMode(gin.ReleaseMode)
	}

	router := gin.New()

	// Load HTML templates if UI is enabled
	if cfg.Server.EnableUI {
		router.LoadHTMLGlob("web/templates/*")
	}

	// Recovery middleware
	router.Use(gin.Recovery())

	// Logging middleware
	router.Use(middleware.LoggingMiddleware())

	// CORS middleware
	if cfg.CORS.Enabled {
		corsConfig := cors.Config{
			AllowOrigins:     cfg.CORS.AllowedOrigins,
			AllowMethods:     []string{"GET", "POST", "PATCH", "DELETE", "OPTIONS"},
			AllowHeaders:     []string{"Origin", "Content-Type", "Authorization"},
			ExposeHeaders:    []string{"Content-Length"},
			AllowCredentials: true,
		}
		router.Use(cors.New(corsConfig))
	}

	// Embedded UI (no auth required, disabled by default)
	uiHandler := handlers.NewUIHandler(cfg.Server.EnableUI)
	router.GET("/", uiHandler.ServeUI)

	// Health check endpoint (no auth required)
	router.GET("/health", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"status":  "ok",
			"service": "taskwarrior-api",
		})
	})

	// Swagger documentation (no auth required)
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// API v1 routes
	v1 := router.Group("/api/v1")
	v1.Use(middleware.AuthMiddleware(validator))

	// Initialize handlers
	taskHandler := handlers.NewTaskHandler(twClient)
	reportHandler := handlers.NewReportHandler(twClient)
	projectHandler := handlers.NewProjectHandler(twClient)

	// Task routes
	tasks := v1.Group("/tasks")
	{
		tasks.GET("", taskHandler.ListTasks)
		tasks.POST("", taskHandler.CreateTask)
		tasks.GET("/:uuid", taskHandler.GetTask)
		tasks.PATCH("/:uuid", taskHandler.UpdateTask)
		tasks.DELETE("/:uuid", taskHandler.DeleteTask)
		tasks.POST("/:uuid/done", taskHandler.DoneTask)
		tasks.POST("/:uuid/start", taskHandler.StartTask)
		tasks.POST("/:uuid/stop", taskHandler.StopTask)
	}

	// Report routes
	reports := v1.Group("/reports")
	{
		reports.GET("", reportHandler.ListReports)
		reports.GET("/:name/tasks", reportHandler.GetReport)
	}

	// Project routes
	projects := v1.Group("/projects")
	{
		projects.GET("", projectHandler.ListProjects)
		projects.GET("/:name/tasks", projectHandler.GetProjectTasks)
	}

	return router
}
